### ISSUE TITLE
Can't configure on windows

### ISSUE THREAD

**Issue by PROinALL** [kvark/vange-rs#129] opened 2020-11-12 20:42 UTC
thread 'main' panicked at 'Can't find the resources of the original Vangers game at "/vange-rs-master/", please check your `config/settings.ron`', src\config\settings.rs:179:13

what does "original Vangers game" represent?
why just don't have default configuration to run cargo run and that's it?

**Comment by kvark** [comment] 2020-11-12 21:03
Dupe of #128

**Closed by kvark** 2020-11-12 21:03 UTC
